export interface ServerDataset {
  id: string;
  product_id: string;
  title: string;
  dataset: string;
  instrument: 'OHRC' | 'TMC-2' | 'IIRS';
  acquisition: string;
  lat: number;
  lon: number;
  region: string;
  sun_elevation: number;
  sun_azimuth: number;
  resolution: string;
  gsd_m: number;
  image_url: string;
  thumbnail_url: string;
  file_size_kb: number;
  width: number;
  height: number;
  status: string;
  source?: string;
  description: string;
  pds4_metadata?: {
    logical_identifier: string;
    version_id: string;
    product_class: string;
    target_name: string;
    mission_phase: string;
    instrument_host_name: string;
    instrument_name: string;
    spacecraft_clock_start: string;
    spacecraft_clock_stop: string;
    incidence_angle_deg: number;
    emission_angle_deg: number;
    phase_angle_deg: number;
    sub_solar_azimuth: number;
    sub_solar_elevation: number;
    radiometric_calibration: string;
    filter_wavelength: string;
  };
}

export const DATASETS_LIST: ServerDataset[] = [
  {
    id: 'ch2_ohr_ncp_20220324T184000_d_img_d18',
    product_id: 'ch2_ohr_ncp_20220324T184000_d_img_d18',
    title: 'OHRC High-Resolution Optical — Tycho Crater (West Sun 265°)',
    dataset: 'OHRC',
    instrument: 'OHRC',
    acquisition: '2022-03-24T18:40:00Z',
    lat: -43.31,
    lon: -11.36,
    region: 'Tycho Crater Rim (West View)',
    sun_elevation: 30.5,
    sun_azimuth: 265.0,
    resolution: '0.25 m/px',
    gsd_m: 0.25,
    image_url: '/images/ch2_ohr_ncp_20220324T184000_d_img_d18.png',
    thumbnail_url: '/thumbnails/ch2_ohr_ncp_20220324T184000_d_img_d18_thumb.png',
    file_size_kb: 4820,
    width: 2048,
    height: 2048,
    status: 'INDEXED',
    description: 'High-resolution 0.25m/px panchromatic optical swath acquired by OHRC over Tycho crater rim under afternoon solar illumination (265° azimuth).',
    pds4_metadata: {
      logical_identifier: 'urn:isro:isda:ch2:ohr:ch2_ohr_ncp_20220324T184000_d_img_d18',
      version_id: '1.0',
      product_class: 'Product_Observational',
      target_name: 'Moon',
      mission_phase: 'Extended Science Phase',
      instrument_host_name: 'Chandrayaan-2 Orbiter',
      instrument_name: 'Orbiter High Resolution Camera (OHRC)',
      spacecraft_clock_start: '687492100.12',
      spacecraft_clock_stop: '687492120.45',
      incidence_angle_deg: 59.5,
      emission_angle_deg: 3.2,
      phase_angle_deg: 62.1,
      sub_solar_azimuth: 265.0,
      sub_solar_elevation: 30.5,
      radiometric_calibration: 'CALIBRATED_L2',
      filter_wavelength: 'Panchromatic (450 - 900 nm)',
    },
  },
  {
    id: 'ch2_ohr_ncp_20220310T061500_d_img_d18',
    product_id: 'ch2_ohr_ncp_20220310T061500_d_img_d18',
    title: 'OHRC High-Resolution Optical — Tycho Crater (East Sun 85°)',
    dataset: 'OHRC',
    instrument: 'OHRC',
    acquisition: '2022-03-10T06:15:00Z',
    lat: -43.31,
    lon: -11.36,
    region: 'Tycho Crater Rim (East View)',
    sun_elevation: 32.0,
    sun_azimuth: 85.0,
    resolution: '0.25 m/px',
    gsd_m: 0.25,
    image_url: '/images/ch2_ohr_ncp_20220310T061500_d_img_d18.png',
    thumbnail_url: '/thumbnails/ch2_ohr_ncp_20220310T061500_d_img_d18_thumb.png',
    file_size_kb: 4820,
    width: 2048,
    height: 2048,
    status: 'INDEXED',
    description: 'High-resolution 0.25m/px panchromatic optical observation of Tycho Crater under morning solar illumination (180° azimuth delta from afternoon swath).',
    pds4_metadata: {
      logical_identifier: 'urn:isro:isda:ch2:ohr:ch2_ohr_ncp_20220310T061500_d_img_d18',
      version_id: '1.0',
      product_class: 'Product_Observational',
      target_name: 'Moon',
      mission_phase: 'Extended Science Phase',
      instrument_host_name: 'Chandrayaan-2 Orbiter',
      instrument_name: 'Orbiter High Resolution Camera (OHRC)',
      spacecraft_clock_start: '686234100.88',
      spacecraft_clock_stop: '686234121.20',
      incidence_angle_deg: 58.0,
      emission_angle_deg: 2.8,
      phase_angle_deg: 60.5,
      sub_solar_azimuth: 85.0,
      sub_solar_elevation: 32.0,
      radiometric_calibration: 'CALIBRATED_L2',
      filter_wavelength: 'Panchromatic (450 - 900 nm)',
    },
  },
  {
    id: 'ch2_ohr_ncp_20191015T041200_d_img_d18',
    product_id: 'ch2_ohr_ncp_20191015T041200_d_img_d18',
    title: 'OHRC High-Resolution Optical — Boguslawsky E Crater',
    dataset: 'OHRC',
    instrument: 'OHRC',
    acquisition: '2019-10-15T04:12:00Z',
    lat: -74.32,
    lon: 53.64,
    region: 'Boguslawsky E Crater (South Pole)',
    sun_elevation: 28.4,
    sun_azimuth: 65.2,
    resolution: '0.25 m/px',
    gsd_m: 0.25,
    image_url: '/images/ch2_ohr_ncp_20191015T041200_d_img_d18.png',
    thumbnail_url: '/thumbnails/ch2_ohr_ncp_20191015T041200_d_img_d18_thumb.png',
    file_size_kb: 4950,
    width: 2048,
    height: 2048,
    status: 'INDEXED',
    description: 'Calibrated panchromatic sub-meter optical frame over high-priority southern landing candidate site Boguslawsky E.',
    pds4_metadata: {
      logical_identifier: 'urn:isro:isda:ch2:ohr:ch2_ohr_ncp_20191015T041200_d_img_d18',
      version_id: '1.0',
      product_class: 'Product_Observational',
      target_name: 'Moon',
      mission_phase: 'Primary Science Phase',
      instrument_host_name: 'Chandrayaan-2 Orbiter',
      instrument_name: 'Orbiter High Resolution Camera (OHRC)',
      spacecraft_clock_start: '611204500.10',
      spacecraft_clock_stop: '611204522.40',
      incidence_angle_deg: 61.6,
      emission_angle_deg: 1.5,
      phase_angle_deg: 62.4,
      sub_solar_azimuth: 65.2,
      sub_solar_elevation: 28.4,
      radiometric_calibration: 'CALIBRATED_L2',
      filter_wavelength: 'Panchromatic (450 - 900 nm)',
    },
  },
  {
    id: 'ch2_tmc_ncn_20200411T093000_d_img_d18',
    product_id: 'ch2_tmc_ncn_20200411T093000_d_img_d18',
    title: 'TMC-2 Panchromatic Terrain Strip — Boguslawsky E',
    dataset: 'TMC-2',
    instrument: 'TMC-2',
    acquisition: '2020-04-11T09:30:00Z',
    lat: -74.32,
    lon: 53.64,
    region: 'Boguslawsky E Crater (South Pole)',
    sun_elevation: 54.1,
    sun_azimuth: 142.8,
    resolution: '5.0 m/px',
    gsd_m: 5.0,
    image_url: '/images/ch2_tmc_ncn_20200411T093000_d_img_d18.png',
    thumbnail_url: '/thumbnails/ch2_tmc_ncn_20200411T093000_d_img_d18_thumb.png',
    file_size_kb: 3240,
    width: 1024,
    height: 1024,
    status: 'INDEXED',
    description: 'Terrain Mapping Camera-2 nadir panchromatic strip providing regional topographic context for cross-scale registration with OHRC.',
    pds4_metadata: {
      logical_identifier: 'urn:isro:isda:ch2:tmc:ch2_tmc_ncn_20200411T093000_d_img_d18',
      version_id: '1.0',
      product_class: 'Product_Observational',
      target_name: 'Moon',
      mission_phase: 'Primary Science Phase',
      instrument_host_name: 'Chandrayaan-2 Orbiter',
      instrument_name: 'Terrain Mapping Camera-2 (TMC-2)',
      spacecraft_clock_start: '626779800.55',
      spacecraft_clock_stop: '626779850.80',
      incidence_angle_deg: 35.9,
      emission_angle_deg: 0.2,
      phase_angle_deg: 36.0,
      sub_solar_azimuth: 142.8,
      sub_solar_elevation: 54.1,
      radiometric_calibration: 'CALIBRATED_L2',
      filter_wavelength: 'Panchromatic (500 - 850 nm)',
    },
  },
  {
    id: 'ch2_tmc_ncn_20210828T144500_d_img_d18',
    product_id: 'ch2_tmc_ncn_20210828T144500_d_img_d18',
    title: 'TMC-2 Panchromatic Terrain Strip — Shackleton Crater Rim',
    dataset: 'TMC-2',
    instrument: 'TMC-2',
    acquisition: '2021-08-28T14:45:00Z',
    lat: -89.90,
    lon: 0.00,
    region: 'Shackleton Crater Rim (South Pole PSR)',
    sun_elevation: 12.4,
    sun_azimuth: 180.0,
    resolution: '5.0 m/px',
    gsd_m: 5.0,
    image_url: '/images/ch2_tmc_ncn_20210828T144500_d_img_d18.png',
    thumbnail_url: '/thumbnails/ch2_tmc_ncn_20210828T144500_d_img_d18_thumb.png',
    file_size_kb: 3180,
    width: 1024,
    height: 1024,
    status: 'INDEXED',
    description: 'TMC-2 stereo terrain imagery capturing the illuminated peaks of eternal light along the rim of Shackleton Crater.',
    pds4_metadata: {
      logical_identifier: 'urn:isro:isda:ch2:tmc:ch2_tmc_ncn_20210828T144500_d_img_d18',
      version_id: '1.0',
      product_class: 'Product_Observational',
      target_name: 'Moon',
      mission_phase: 'Extended Science Phase',
      instrument_host_name: 'Chandrayaan-2 Orbiter',
      instrument_name: 'Terrain Mapping Camera-2 (TMC-2)',
      spacecraft_clock_start: '668270700.22',
      spacecraft_clock_stop: '668270755.90',
      incidence_angle_deg: 77.6,
      emission_angle_deg: 1.1,
      phase_angle_deg: 78.2,
      sub_solar_azimuth: 180.0,
      sub_solar_elevation: 12.4,
      radiometric_calibration: 'CALIBRATED_L2',
      filter_wavelength: 'Panchromatic (500 - 850 nm)',
    },
  },
  {
    id: 'ch2_iir_ncn_20210828T144500_d_cub_d18',
    product_id: 'ch2_iir_ncn_20210828T144500_d_cub_d18',
    title: 'IIRS Hyperspectral Cube (Band 120: 2.1 µm) — Shackleton Rim',
    dataset: 'IIRS',
    instrument: 'IIRS',
    acquisition: '2021-08-28T14:45:00Z',
    lat: -89.90,
    lon: 0.00,
    region: 'Shackleton Crater Rim (South Pole PSR)',
    sun_elevation: 12.4,
    sun_azimuth: 180.0,
    resolution: '80.0 m/px',
    gsd_m: 80.0,
    image_url: '/images/ch2_iir_ncn_20210828T144500_d_cub_d18.png',
    thumbnail_url: '/thumbnails/ch2_iir_ncn_20210828T144500_d_cub_d18_thumb.png',
    file_size_kb: 8940,
    width: 512,
    height: 512,
    status: 'INDEXED',
    description: 'Imaging Infra-red Spectrometer 256-channel spectral cube extracting 2.1 µm OH/H2O diagnostic absorption band for cross-modal correspondence.',
    pds4_metadata: {
      logical_identifier: 'urn:isro:isda:ch2:iir:ch2_iir_ncn_20210828T144500_d_cub_d18',
      version_id: '1.0',
      product_class: 'Product_Observational',
      target_name: 'Moon',
      mission_phase: 'Extended Science Phase',
      instrument_host_name: 'Chandrayaan-2 Orbiter',
      instrument_name: 'Imaging Infra-red Spectrometer (IIRS)',
      spacecraft_clock_start: '668270700.22',
      spacecraft_clock_stop: '668270755.90',
      incidence_angle_deg: 77.6,
      emission_angle_deg: 1.1,
      phase_angle_deg: 78.2,
      sub_solar_azimuth: 180.0,
      sub_solar_elevation: 12.4,
      radiometric_calibration: 'CALIBRATED_L2_REFLECTANCE',
      filter_wavelength: 'Infrared (0.8 - 5.0 µm, 256 bands)',
    },
  },
  {
    id: 'DS-OHRC-BOGUSLAWSKY-01',
    product_id: 'DS-OHRC-BOGUSLAWSKY-01',
    title: 'OHRC High-Resolution Optical — Boguslawsky E South',
    dataset: 'OHRC',
    instrument: 'OHRC',
    acquisition: '2024-03-14T08:24:19Z',
    lat: -72.9,
    lon: 43.2,
    region: 'Boguslawsky Crater (South Polar)',
    sun_elevation: 18.2,
    sun_azimuth: 48.5,
    resolution: '0.25 m/px',
    gsd_m: 0.25,
    image_url: '/images/DS-OHRC-BOGUSLAWSKY-01.png',
    thumbnail_url: '/thumbnails/DS-OHRC-BOGUSLAWSKY-01_thumb.png',
    file_size_kb: 4820,
    width: 2048,
    height: 2048,
    status: 'INDEXED',
    description: 'Sub-meter hazard avoidance reference frame for polar landing site verification.',
    pds4_metadata: {
      logical_identifier: 'urn:isro:isda:ch2:ohr:ds_ohrc_boguslawsky_01',
      version_id: '1.0',
      product_class: 'Product_Observational',
      target_name: 'Moon',
      mission_phase: 'Extended Phase',
      instrument_host_name: 'Chandrayaan-2 Orbiter',
      instrument_name: 'Orbiter High Resolution Camera (OHRC)',
      spacecraft_clock_start: '763294100.00',
      spacecraft_clock_stop: '763294120.00',
      incidence_angle_deg: 71.8,
      emission_angle_deg: 2.1,
      phase_angle_deg: 73.0,
      sub_solar_azimuth: 48.5,
      sub_solar_elevation: 18.2,
      radiometric_calibration: 'CALIBRATED_L2',
      filter_wavelength: 'Panchromatic (450 - 900 nm)',
    },
  },
  {
    id: 'DS-TMC2-BOGUSLAWSKY-01',
    product_id: 'DS-TMC2-BOGUSLAWSKY-01',
    title: 'TMC-2 Panchromatic Terrain Strip — Boguslawsky Context',
    dataset: 'TMC-2',
    instrument: 'TMC-2',
    acquisition: '2024-03-14T08:24:19Z',
    lat: -72.9,
    lon: 43.2,
    region: 'Boguslawsky Crater (South Polar)',
    sun_elevation: 19.0,
    sun_azimuth: 52.0,
    resolution: '5.0 m/px',
    gsd_m: 5.0,
    image_url: '/images/DS-TMC2-BOGUSLAWSKY-01.png',
    thumbnail_url: '/thumbnails/DS-TMC2-BOGUSLAWSKY-01_thumb.png',
    file_size_kb: 3240,
    width: 1024,
    height: 1024,
    status: 'INDEXED',
    description: 'Terrain Mapping Camera-2 stereo strip for digital elevation reconstruction and multi-scale matching.',
    pds4_metadata: {
      logical_identifier: 'urn:isro:isda:ch2:tmc:ds_tmc2_boguslawsky_01',
      version_id: '1.0',
      product_class: 'Product_Observational',
      target_name: 'Moon',
      mission_phase: 'Extended Phase',
      instrument_host_name: 'Chandrayaan-2 Orbiter',
      instrument_name: 'Terrain Mapping Camera-2 (TMC-2)',
      spacecraft_clock_start: '763294100.00',
      spacecraft_clock_stop: '763294150.00',
      incidence_angle_deg: 71.0,
      emission_angle_deg: 0.5,
      phase_angle_deg: 71.5,
      sub_solar_azimuth: 52.0,
      sub_solar_elevation: 19.0,
      radiometric_calibration: 'CALIBRATED_L2',
      filter_wavelength: 'Panchromatic (500 - 850 nm)',
    },
  },
  {
    id: 'DS-IIRS-SHACKLETON-02',
    product_id: 'DS-IIRS-SHACKLETON-02',
    title: 'IIRS Hyperspectral Infrared (2.1 µm) — Shackleton Ridge',
    dataset: 'IIRS',
    instrument: 'IIRS',
    acquisition: '2024-04-02T14:10:05Z',
    lat: -89.9,
    lon: 0.0,
    region: 'Shackleton Rim (Lunar South Pole)',
    sun_elevation: 9.0,
    sun_azimuth: 115.0,
    resolution: '80.0 m/px',
    gsd_m: 80.0,
    image_url: '/images/DS-IIRS-SHACKLETON-02.png',
    thumbnail_url: '/thumbnails/DS-IIRS-SHACKLETON-02_thumb.png',
    file_size_kb: 8940,
    width: 512,
    height: 512,
    status: 'INDEXED',
    description: 'Hyperspectral absorption feature observation for volatile mapping in permanently shadowed polar regions.',
    pds4_metadata: {
      logical_identifier: 'urn:isro:isda:ch2:iir:ds_iirs_shackleton_02',
      version_id: '1.0',
      product_class: 'Product_Observational',
      target_name: 'Moon',
      mission_phase: 'Extended Phase',
      instrument_host_name: 'Chandrayaan-2 Orbiter',
      instrument_name: 'Imaging Infra-red Spectrometer (IIRS)',
      spacecraft_clock_start: '764950205.00',
      spacecraft_clock_stop: '764950250.00',
      incidence_angle_deg: 81.0,
      emission_angle_deg: 0.8,
      phase_angle_deg: 81.8,
      sub_solar_azimuth: 115.0,
      sub_solar_elevation: 9.0,
      radiometric_calibration: 'CALIBRATED_L2_REFLECTANCE',
      filter_wavelength: 'Infrared (0.8 - 5.0 µm, 256 bands)',
    },
  },
  {
    id: 'DS-OHRC-TYCHO-AM-03',
    product_id: 'DS-OHRC-TYCHO-AM-03',
    title: 'OHRC High-Resolution Optical — Tycho Crater Morning Illumination',
    dataset: 'OHRC',
    instrument: 'OHRC',
    acquisition: '2024-05-18T05:14:00Z',
    lat: -43.3,
    lon: -11.2,
    region: 'Tycho Crater Rim (Central Peak Area)',
    sun_elevation: 24.5,
    sun_azimuth: 82.0,
    resolution: '0.25 m/px',
    gsd_m: 0.25,
    image_url: '/images/DS-OHRC-TYCHO-AM-03.png',
    thumbnail_url: '/thumbnails/DS-OHRC-TYCHO-AM-03_thumb.png',
    file_size_kb: 4890,
    width: 2048,
    height: 2048,
    status: 'INDEXED',
    description: 'Morning low-angle solar illumination revealing boulder fields and impact melt terraces on Tycho rim.',
    pds4_metadata: {
      logical_identifier: 'urn:isro:isda:ch2:ohr:ds_ohrc_tycho_am_03',
      version_id: '1.0',
      product_class: 'Product_Observational',
      target_name: 'Moon',
      mission_phase: 'Extended Phase',
      instrument_host_name: 'Chandrayaan-2 Orbiter',
      instrument_name: 'Orbiter High Resolution Camera (OHRC)',
      spacecraft_clock_start: '768882840.00',
      spacecraft_clock_stop: '768882860.00',
      incidence_angle_deg: 65.5,
      emission_angle_deg: 1.2,
      phase_angle_deg: 66.0,
      sub_solar_azimuth: 82.0,
      sub_solar_elevation: 24.5,
      radiometric_calibration: 'CALIBRATED_L2',
      filter_wavelength: 'Panchromatic (450 - 900 nm)',
    },
  },
  {
    id: 'DS-OHRC-TYCHO-PM-03',
    product_id: 'DS-OHRC-TYCHO-PM-03',
    title: 'OHRC High-Resolution Optical — Tycho Crater Evening Illumination',
    dataset: 'OHRC',
    instrument: 'OHRC',
    acquisition: '2024-05-30T17:42:10Z',
    lat: -43.3,
    lon: -11.2,
    region: 'Tycho Crater Rim (Central Peak Area)',
    sun_elevation: 26.0,
    sun_azimuth: 268.0,
    resolution: '0.25 m/px',
    gsd_m: 0.25,
    image_url: '/images/DS-OHRC-TYCHO-PM-03.png',
    thumbnail_url: '/thumbnails/DS-OHRC-TYCHO-PM-03_thumb.png',
    file_size_kb: 4890,
    width: 2048,
    height: 2048,
    status: 'INDEXED',
    description: 'Opposing shadow vector frame acquired at 268° solar azimuth for sun-angle invariant correspondence testing.',
    pds4_metadata: {
      logical_identifier: 'urn:isro:isda:ch2:ohr:ds_ohrc_tycho_pm_03',
      version_id: '1.0',
      product_class: 'Product_Observational',
      target_name: 'Moon',
      mission_phase: 'Extended Phase',
      instrument_host_name: 'Chandrayaan-2 Orbiter',
      instrument_name: 'Orbiter High Resolution Camera (OHRC)',
      spacecraft_clock_start: '769964530.00',
      spacecraft_clock_stop: '769964550.00',
      incidence_angle_deg: 64.0,
      emission_angle_deg: 2.5,
      phase_angle_deg: 66.5,
      sub_solar_azimuth: 268.0,
      sub_solar_elevation: 26.0,
      radiometric_calibration: 'CALIBRATED_L2',
      filter_wavelength: 'Panchromatic (450 - 900 nm)',
    },
  },
  {
    id: 'DS-TMC2-SHACKLETON-02',
    product_id: 'DS-TMC2-SHACKLETON-02',
    title: 'TMC-2 Panchromatic Terrain Strip — Shackleton Polar Ridge',
    dataset: 'TMC-2',
    instrument: 'TMC-2',
    acquisition: '2024-04-02T14:10:05Z',
    lat: -89.9,
    lon: 0.0,
    region: 'Shackleton Rim (Lunar South Pole)',
    sun_elevation: 9.0,
    sun_azimuth: 115.0,
    resolution: '5.0 m/px',
    gsd_m: 5.0,
    image_url: '/images/DS-TMC2-SHACKLETON-02.png',
    thumbnail_url: '/thumbnails/DS-TMC2-SHACKLETON-02_thumb.png',
    file_size_kb: 3220,
    width: 1024,
    height: 1024,
    status: 'INDEXED',
    description: 'Co-registered stereo strip for South Pole illumination profiling and terrain roughness correlation.',
    pds4_metadata: {
      logical_identifier: 'urn:isro:isda:ch2:tmc:ds_tmc2_shackleton_02',
      version_id: '1.0',
      product_class: 'Product_Observational',
      target_name: 'Moon',
      mission_phase: 'Extended Phase',
      instrument_host_name: 'Chandrayaan-2 Orbiter',
      instrument_name: 'Terrain Mapping Camera-2 (TMC-2)',
      spacecraft_clock_start: '764950205.00',
      spacecraft_clock_stop: '764950250.00',
      incidence_angle_deg: 81.0,
      emission_angle_deg: 0.5,
      phase_angle_deg: 81.5,
      sub_solar_azimuth: 115.0,
      sub_solar_elevation: 9.0,
      radiometric_calibration: 'CALIBRATED_L2',
      filter_wavelength: 'Panchromatic (500 - 850 nm)',
    },
  },
];

export const DEFAULT_MATCHES = Array.from({ length: 120 }).map((_, i) => {
  const sx = ((i * 47) % 860) + 70;
  const sy = ((i * 71) % 860) + 70;
  const isInlier = i % 9 !== 0;
  return {
    id: i + 1,
    source_x: sx,
    source_y: sy,
    target_x: sx + (isInlier ? (Math.sin(i) * 2.5 - 1.2) : 55.0),
    target_y: sy + (isInlier ? (Math.cos(i) * 2.5 + 1.2) : -45.0),
    reference_x: sx + (isInlier ? (Math.sin(i) * 2.5 - 1.2) : 55.0),
    reference_y: sy + (isInlier ? (Math.cos(i) * 2.5 + 1.2) : -45.0),
    match_type: isInlier ? 'INLIER' : 'OUTLIER',
    inlier: isInlier,
    is_inlier: isInlier,
    confidence: isInlier ? 0.94 : 0.20,
    reprojection_error_px: isInlier ? 0.22 : 12.4,
  };
});

export const DEFAULT_REPORT = {
  analysis_id: 'RUN-20261004-95D6E5',
  id: 'RUN-20261004-95D6E5',
  title: 'Chandrayaan-2 Planetary Correspondence Report — RUN-20261004-95D6E5',
  created_at: '2026-10-04 12:30:15 UTC',
  algorithm: 'LoFTR Deep Planetary Transformer + Pyramidal Wallis + RANSAC',
  classification: 'HIGH PRECISION SCIENTIFIC CORRESPONDENCE',
  confidence: 98.4,
  source: {
    id: 'ch2_ohr_ncp_20220324T184000_d_img_d18',
    payload: 'OHRC',
    region: 'Tycho Crater Rim (South Polar)',
    resolution: 0.25,
    sun_elevation: 30.5,
    sun_azimuth: 265.0,
    acquisition: '2022-03-24T18:40:00Z',
    width: 2048,
    height: 2048,
  },
  target: {
    id: 'ch2_ohr_ncp_20220310T061500_d_img_d18',
    payload: 'OHRC',
    region: 'Tycho Crater Rim (South Polar)',
    resolution: 0.25,
    sun_elevation: 32.0,
    sun_azimuth: 85.0,
    acquisition: '2022-03-10T06:15:00Z',
    width: 2048,
    height: 2048,
  },
  metrics: {
    verified_inliers: 429,
    outliers: 53,
    total_candidates: 482,
    inlier_ratio_pct: 89.0,
    registration_error_rmse_px: 0.38,
    spatial_coverage_pct: 94.2,
    scale_ratio: 1.0,
    sun_elevation_delta: 1.5,
    sun_azimuth_delta: 180.0,
  },
  matches: DEFAULT_MATCHES,
};


